### ISSUE TITLE
Crash converting to PDF via any converter other than iText

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dbarra/xdocreport#112]
```
What steps will reproduce the problem?
1. Run sample Java files in the docxandvelocity.converters-0.9.7-sample.zip but 
change the Options to convert to PDF via FOP (or any other ConverterTypeVia 
except iText).
2. Project crashes.
3.

What is the expected output? What do you see instead?
Expected output is a generated PDF via the required converter. Project crashes 
instead.

What version of the product are you using? On what operating system?
0.9.7 from docxandvelocity.converters-0.9.7-sample.zip on Windows 7

Please provide any additional information below.
Tried on all of your sample java files with the same crash. Only conversion 
method that works is via iText. See stack trace below:

30-Apr-2012 11:45:37 fr.opensagres.xdocreport.converter.ConverterRegistry 
internalFindConverter
SEVERE: Cannot find converters via FOP for to=PDF for from=DOCX
fr.opensagres.xdocreport.converter.XDocConverterException: Cannot find 
converters via FOP for to=PDF for from=DOCX
    at fr.opensagres.xdocreport.converter.ConverterRegistry.internalFindConverter(ConverterRegistry.java:158)
    at fr.opensagres.xdocreport.converter.ConverterRegistry.findConverter(ConverterRegistry.java:74)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.getConverter(AbstractXDocReport.java:646)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:663)
    at fr.opensagres.xdocreport.samples.docxandvelocity.DocxProjectWithVelocity2PDF.main(DocxProjectWithVelocity2PDF.java:207)

```

Original issue reported on code.google.com by `xnix...@gmail.com` on 30 Apr 2012 at 10:47

Attachments:
- [DocxProjectWithVelocity2PDF.java](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-112/comment-0/DocxProjectWithVelocity2PDF.java)
- [DocxProjectWithVelocity.docx](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-112/comment-0/DocxProjectWithVelocity.docx)

**Comment by GoogleCodeExporter** [comment]
```
Forgot to mention that I've tried with conversion to PDF from both DOCX and ODT
```

Original comment by `xnix...@gmail.com` on 30 Apr 2012 at 12:01

**Comment by GoogleCodeExporter** [comment]
```
Please note that FOP based converter is only an experimental feature. AS you 
can see in the repo :
http://code.google.com/p/xdocreport/source/browse/#git%2Fsandbox
the implementation is under a "sandbox" subfolder.

We don't have currently the workforce to improve It. Would you like to 
contribute ?
```

Original comment by `pascal.leclercq` on 1 May 2012 at 6:59

**Comment by GoogleCodeExporter** [comment]
```
Hi,

As Pascal said, FOP implementation is just experimental work.
XDocReport is very modular, so you can implement any converter and use it. To 
use a converter, the JAR of teh converter must be in your CLASSPATH.

So your problem is that you have not putted the FOP converter implementation in 
your classpath. But the result of this converter is very bad.

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 3 May 2012 at 1:53
- Changed state: **Invalid**
