### ISSUE TITLE
itext-gae instead of itext

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dbarra/xdocreport#197]
```
What steps will reproduce the problem?
1. Install XDocReports jar's in a Google App Engine project
2. Use itext-gae.jar instead of itext-2.1.7.jar for PDF generation (check 
http://blog.rubypdf.com/2009/12/17/how-to-run-itext-on-google-app-engine/)
3. getting StackOverflowError at 
com.lowagie.text.pdf.RandomAccessFileOrArray.seek(

What is the expected output? What do you see instead?
It would be nice if it worked

What version of the product are you using? On what operating system?
Google App Engine latest version

Please provide any additional information below.


```

Original issue reported on code.google.com by `santilh@gmail.com` on 26 Nov 2012 at 1:12

**Comment by GoogleCodeExporter** [comment]
```
Hi santhil,

At first, you have problem with odt->pdf or docx->pdf converter. Have you 
problem with your odt/docx by using itext-2.1.7.jar (not Google App Engine)?

If it's a problem with itext-gae.jar, do you think we can create a simple Java 
main (not Google App Engine context) to launch the converter? I tell you that 
because I don't know Google App Engine.

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 26 Nov 2012 at 1:21
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
santhil,

I'm not able to test, but I suspect the problem come from the "boolean 
plainRandomAccess" of  RandomAccessFileOrArray which must be set to true in any 
case.

Can you please test with the jar provided and/ tell us how to test.


```

Original comment by `pascal.leclercq` on 27 Nov 2012 at 8:51

Attachments:
- [iText-2.1.7-gae.jar](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-197/comment-2/iText-2.1.7-gae.jar)

**Comment by GoogleCodeExporter** [comment]
```
Problem is fixed with our her itext-gae. Please read 
http://code.google.com/p/xdocreport/wiki/XDocReportGAE
```

Original comment by `angelo.z...@gmail.com` on 7 Jan 2013 at 1:04
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi Angelo,

I just submitted a reply on the wiki about the new enhancement (good job btw). 
It would be nice if you could help me reproduce the xdocreport-gae project in 
my local development environment. As commented, I am running into the following 
traceback:

{{{java.lang.NoClassDefFoundError: javax.management.ObjectName is a restricted 
class. Please see the Google  App Engine developer's guide for more details.
    at com.google.appengine.tools.development.agent.runtime.Runtime.reject(Runtime.java:51)
    at org.apache.cxf.endpoint.ManagedEndpoint.getObjectName(ManagedEndpoint.java:101)
    at org.apache.cxf.management.jmx.InstrumentationManagerImpl.register(InstrumentationManagerImpl.java:245)
    at org.apache.cxf.management.jmx.InstrumentationManagerImpl.register(InstrumentationManagerImpl.java:239)
    at org.apache.cxf.endpoint.ServerImpl.initDestination(ServerImpl.java:107)
    at org.apache.cxf.endpoint.ServerImpl.<init>(ServerImpl.java:72)
    at org.apache.cxf.jaxrs.JAXRSServerFactoryBean.create(JAXRSServerFactoryBean.java:155)
    at org.apache.cxf.jaxrs.servlet.CXFNonSpringJaxrsServlet.init(CXFNonSpringJaxrsServlet.java:140)
    at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
    at org.mortbay.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:339)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
    at com.google.appengine.api.socket.dev.DevSocketFilter.doFilter(DevSocketFilter.java:74)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.ResponseRewriterFilter.doFilter(ResponseRewriterFilter.java:123)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.HeaderVerificationFilter.doFilter(HeaderVerificationFilter.java:34)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:61)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.StaticFileFilter.doFilter(StaticFileFilter.java:125)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at com.google.appengine.tools.development.BackendServersFilter.doFilter(BackendServersFilter.java:97)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
    at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:94)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:383)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)}}}

and enclosed is my project. 
(https://dl.dropboxusercontent.com/u/10435954/xdocreport-gae.rar)
```

Original comment by `santilh@gmail.com` on 14 Apr 2013 at 2:12

**Comment by GoogleCodeExporter** [comment]
```
Santilh,

on the dev branch, weuse https://github.com/pascalleclercq/itext-gae which is a 
fork of https://github.com/witwall/itext-gae

You can see a demo of the converter running on GAE:
http://xdocreport-gae.appspot.com/

Cqn yu pleqse give a try to our dev branch ? I suppose your problem is already 
solved. If It's not the case we'll need to select the best available itext-gae 
jar.


Best regards

```

Original comment by `pascal.leclercq` on 15 Apr 2013 at 4:23
