### ISSUE TITLE
Help me for convert docx to pdf with XDocReport 10.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dbarra/xdocreport#228]
```
I did like the Docx Reporting in WEB Application with Dispatcher for Google App 
Engine.

The version which i tried are docxandvelocity.converters-1.0.0 and 10.1 and for 
xx-gae.jar is also.

And the result to docx report is no problem but when i give the parameter 
converter=PDF_ITEXT is error 

XDocReport Servlet: Error report generation
Cannot find converters via ITEXT for to=PDF for 
from=DOCXfr.opensagres.xdocreport.converter.XDocConverterException: Cannot find 
converters via ITEXT for to=PDF for from=DOCX
    at fr.opensagres.xdocreport.converter.ConverterRegistry.internalFindConverter(ConverterRegistry.java:158)
    at fr.opensagres.xdocreport.converter.ConverterRegistry.findConverter(ConverterRegistry.java:74)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.getConverter(AbstractXDocReport.java:664)
    at fr.opensagres.xdocreport.document.web.AbstractProcessXDocReportServlet.doProcessReportWithConverter(AbstractProcessXDocReportServlet.java:319)
    at fr.opensagres.xdocreport.document.web.AbstractProcessXDocReportServlet.doGenerateReport(AbstractProcessXDocReportServlet.java:246)
    at fr.opensagres.xdocreport.document.web.AbstractProcessXDocReportServlet.processRequest(AbstractProcessXDocReportServlet.java:111)
    at fr.opensagres.xdocreport.document.web.BaseXDocReportServlet.doGet(BaseXDocReportServlet.java:78)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:362)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:729)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.handler.RequestLogHandler.handle(RequestLogHandler.java:49)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:324)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:829)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:513)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:395)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:488)



```

Original issue reported on code.google.com by `administ...@iessystem.com` on 21 Feb 2013 at 2:54

Attachments:
- [DocxProjectWithVelocityController.java](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-228/comment-0/DocxProjectWithVelocityController.java)
- [MyDispatcher.java](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-228/comment-0/MyDispatcher.java)

**Comment by GoogleCodeExporter** [comment]
```

1) Please check you have fr.opensagres.xdocreport.converter.docx.xwpf  in your 
classpath wich register the IConverter for docx->pdf via iText.

2) please try converter=PDF_XWPF
```

Original comment by `angelo.z...@gmail.com` on 21 Feb 2013 at 3:05
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
1. The lib's image  list.
2. Passed.

Thank you very much.
```

Original comment by `administ...@iessystem.com` on 21 Feb 2013 at 3:57

Attachments:
- [lib.png](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-228/comment-3/lib.png)

**Comment by GoogleCodeExporter** [comment]
```
"2. Passed" means that it works?
```

Original comment by `angelo.z...@gmail.com` on 21 Feb 2013 at 9:01

**Comment by GoogleCodeExporter** [comment]
```
Yes, It works.
```

Original comment by `administ...@iessystem.com` on 26 Feb 2013 at 10:31

**Comment by GoogleCodeExporter** [comment]
```
Ok that's cool, you should do too just converter=PDF if in your classpath you 
have just one PDF converter.

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 26 Feb 2013 at 10:42
- Changed state: **Invalid**
