### ISSUE TITLE
Nesting tables within in cells in ODT files causes SAXParseExecption

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dbarra/xdocreport#23]
```
What steps will reproduce the problem?
1. Create a project using the sample ODT2PDF project 
(ODTProjectWithVelocity2PDF.java).
2. Point the InputStream to the attached file (invoiceTemplate.odt).  This is a 
stripped down file that features a table within a cell.

What is the expected output? What do you see instead?
You expect to get a .pdf representation of the .odt file.  Instead, the 
following exception is encountered:

[Fatal Error] :1:5455: The element type "table:table-cell" must be terminated 
by the matching end-tag "</table:table-cell>".
Jul 28, 2011 2:42:26 PM org.odftoolkit.odfdom.pkg.OdfFileDom initialize
SEVERE: null
org.xml.sax.SAXParseException: The element type "table:table-cell" must be 
terminated by the matching end-tag "</table:table-cell>".
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at org.odftoolkit.odfdom.pkg.OdfFileDom.initialize(OdfFileDom.java:142)
    at org.odftoolkit.odfdom.dom.OdfContentDom.initialize(OdfContentDom.java:55)
    at org.odftoolkit.odfdom.pkg.OdfFileDom.<init>(OdfFileDom.java:87)
    at org.odftoolkit.odfdom.dom.OdfContentDom.<init>(OdfContentDom.java:45)
    at org.odftoolkit.odfdom.pkg.OdfFileDom.newFileDom(OdfFileDom.java:110)
    at org.odftoolkit.odfdom.pkg.OdfPackageDocument.getFileDom(OdfPackageDocument.java:281)
    at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getFileDom(OdfSchemaDocument.java:312)
    at org.odftoolkit.odfdom.dom.OdfSchemaDocument.getContentDom(OdfSchemaDocument.java:190)
    at org.odftoolkit.odfdom.converter.itext.ODF2PDFViaITextConverter.doConvert(ODF2PDFViaITextConverter.java:57)
    at org.odftoolkit.odfdom.converter.itext.ODF2PDFViaITextConverter.doConvert(ODF2PDFViaITextConverter.java:41)
    at org.odftoolkit.odfdom.converter.internal.AbstractODFConverter.convert(AbstractODFConverter.java:42)
    at fr.opensagres.xdocreport.converter.odt.odfdom.itext.ODF2PDFViaITextConverter.convert(ODF2PDFViaITextConverter.java:53)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:554)
    at fr.opensagres.xdocreport.samples.odtandvelocity.ODTProjectWithVelocity2PDF.main(ODTProjectWithVelocity2PDF.java:56)


What version of the product are you using? On what operating system?
0.9.0-SNAPSHOT

Please provide any additional information below.
I've isolated the problem to AbstractXDocReport.doPreprocessorIfNeeded().  If 
you avoid this call at line 536 of AbstractXDocReport.convert(), the table 
prints out fine.  Even putting vars in the IContext will work.  But I'm sure 
doPreprocessorIfNeeded() does something important.  Perhaps exposing the 
setting for AbstractXDocReport.preprocessed would be helpful as it would allow 
the user to bypass this operating.

Let me know if I can be of assistance.  Thanks for a cool product and I look 
forward to more great things!

Thanks, Ryan


```

Original issue reported on code.google.com by `ryancut...@gmail.com` on 28 Jul 2011 at 9:49

Attachments:
- [invoiceTemplate.odt](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-23/comment-0/invoiceTemplate.odt)

**Comment by GoogleCodeExporter** [comment]
```
Hi Ryan,

Preprocessing step is very important to manage lazy script (Fremarker, 
Velocity) loop for table row. So this step must be done. Your problem is a bug, 
that I must fix it. Thanks for creating this issue.

Regards Angelo


```

Original comment by `angelo.z...@gmail.com` on 29 Jul 2011 at 12:00
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Hy Ryan,

I have fixed the problem and commited to the SVN.

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 29 Jul 2011 at 8:38

**Comment by GoogleCodeExporter** [comment]
Original comment by `angelo.z...@gmail.com` on 1 Nov 2011 at 6:51
- Changed state: **Fixed**
