### ISSUE TITLE
issue Could not find template in cache

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dbarra/xdocreport#307]
```
I am using a template without any issue, but when i make any change in the docx 
file and save i have the following issue, can u tell me its because of the 
template or something wrong with my code?



_DOMAIN:AdminServer/360])/360
11014 [[ACTIVE] ExecuteThread: '15' for queue: 'weblogic.kernel.Default 
(self-tuning)'] DEBUG freemarker.cache  - Could not find template in cache, 
creating new one; i
["fr.opensagres.xdocreport.document.docx.DocxReport@168fbaa!word/document.xml"["
en_US",UTF-8,parsed] ]
11014 [[ACTIVE] ExecuteThread: '15' for queue: 'weblogic.kernel.Default 
(self-tuning)'] DEBUG freemarker.cache  - Compiling FreeMarker template 
"fr.opensagres.xdocrepo
.document.docx.DocxReport@168fbaa!word/document.xml"["en_US",UTF-8,parsed]  
from "fr.opensagres.xdocreport.core.io.XDocArchive$XDocArchiveEntryInfo@19f5003"
reemarker.core.ParseException: Token manager error: 
freemarker.core.TokenMgrError: Lexical error at line 3, column 23175.  
Encountered: "*" (42), after : "\\" in fr.op
sagres.xdocreport.document.docx.DocxReport@168fbaa!word/document.xml
       at freemarker.template.Template.<init>(Template.java:174)
       at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:447)
       at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:360)
```

Original issue reported on code.google.com by `oueslatibilel216@gmail.com` on 25 Sep 2013 at 9:10

**Comment by GoogleCodeExporter** [comment]
```
Have you tried to save the same docx than docx used in the first time (which 
works)?

If it works, it means that your docx that you have changed is not a valid docx 
report otherwise perhaps it's a bug?
```

Original comment by `angelo.z...@gmail.com` on 25 Sep 2013 at 9:27
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```

Yes that is what i am suggestion too, the docx x is not valid.i will try to 
find out where exactly

Thank you
Bilel
```

Original comment by `oueslatibilel216@gmail.com` on 25 Sep 2013 at 9:53

**Comment by GoogleCodeExporter** [comment]
```
Ok I close this issue.
```

Original comment by `angelo.z...@gmail.com` on 27 Sep 2013 at 11:25
- Changed state: **Invalid**
