### ISSUE TITLE
Encountered: "#" (35), after  : "" 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dbarra/xdocreport#322]
```
What steps will reproduce the problem?
1. I Have a very simple docx document 'see attachment) which contains :
«[#if etapes_nb = 1]world[#else]not world»
«[#if etapes_nb != 1]world[#else]not worl»

2.I got the following error when using freemarker and 
fr.opensagres.xdocreport.***.1.0.2

Caused by: freemarker.core.ParseException: Token manager error: freemarker.core.
TokenMgrError: Lexical error at line 3, column 75.  Encountered: "#" (35), after
 : "" in fr.opensagres.xdocreport.document.docx.DocxReport@f6ff1f!word/document.
xml
        at freemarker.template.Template.<init>(Template.java:152)
        at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:457)
        at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:370)
        at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:238)
        at freemarker.template.Configuration.getTemplate(Configuration.java:493)

        at freemarker.template.Configuration.getTemplate(Configuration.java:458)

        at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine
.processWithCache(FreemarkerTemplateEngine.java:97)
        at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(Abst
ractTemplateEngine.java:111)
        at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(Abst
ractTemplateEngine.java:83)
        at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateE
ngine(AbstractXDocReport.java:772)
        at fr.opensagres.xdocreport.document.AbstractXDocReport.process(Abstract
XDocReport.java:518)
        at fr.opensagres.xdocreport.document.AbstractXDocReport.process(Abstract
XDocReport.java:484)
What version of the product are you using? On what operating system?


Do you have any idea what is wrong?
thanks 
Régis
```

Original issue reported on code.google.com by `rba...@gmail.com` on 12 Nov 2013 at 4:34

Attachments:
- [test.docx](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-322/comment-0/test.docx)

**Comment by GoogleCodeExporter** [comment]
```
Hi Régis,

I have tried with 1.0.3 and it works, I think it should work with 1.0.2 I think.

Please try with 1.0.3 or attach a simple Java main+docx which causes the 
problem.

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 12 Nov 2013 at 9:45
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Hi Angelo,
thanks for your reply.
I retry with 1.0.3 and got the same error:
Running SimpleTest
09:42:31,095 DEBUG [SimpleTest] in :java.io.BufferedInputStream@1cfb549
09:42:31,096 DEBUG [SimpleTest] myValues :{etapes_nb=1}
09:42:31,097 DEBUG [SimpleTest] myConfig :{etapes_nb=Html}
09:42:31,098 DEBUG [SimpleTest] outjava.io.FileOutputStream@f9f9d8
09:42:31,628 DEBUG [freemarker.cache] Could not find template in cache, 
creating new one; 
id=[fr.opensagres.xdocreport.document.docx.DocxReport@b166b5!word/document.xml[f
r_FR,UTF-8,parsed] ]
09:42:31,630 DEBUG [freemarker.cache] Compiling FreeMarker template 
fr.opensagres.xdocreport.document.docx.DocxReport@b166b5!word/document.xml[fr_FR
,UTF-8,parsed]  from 
fr.opensagres.xdocreport.core.io.XDocArchive$XDocArchiveEntryInfo@406199
freemarker.core.ParseException: Token manager error: 
freemarker.core.TokenMgrError: Lexical error at line 3, column 75.  
Encountered: "#" (35), after : "" in 
fr.opensagres.xdocreport.document.docx.DocxReport@b166b5!word/document.xml
    at freemarker.template.Template.<init>(Template.java:152)
    at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:448)
    at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:361)
    at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:235)
    at freemarker.template.Configuration.getTemplate(Configuration.java:487)
    at freemarker.template.Configuration.getTemplate(Configuration.java:452)
    at fr.opensagres.xdocreport.template.freemarker.FreemarkerTemplateEngine.processWithCache(FreemarkerTemplateEngine.java:98)
    at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:111)
    at fr.opensagres.xdocreport.template.AbstractTemplateEngine.process(AbstractTemplateEngine.java:83)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.processTemplateEngine(AbstractXDocReport.java:775)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:521)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.process(AbstractXDocReport.java:487)
    at SimpleTest.xDocReportTemplateGenerator(SimpleTest.java:71)
    at SimpleTest.testIf(SimpleTest.java:38)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.891 sec - in 
SimpleTest

I attached the docx and test java.
thanks for your help
Regards
Regis

```

Original comment by `rba...@gmail.com` on 13 Nov 2013 at 8:46

Attachments:
- [testIf.docx](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-322/comment-2/testIf.docx)
- [SimpleTest.java](https://storage.googleapis.com/google-code-attachments/xdocreport/issue-322/comment-2/SimpleTest.java)

**Comment by GoogleCodeExporter** [comment]
```
You have forgotten to tell me that you use SyntaxKind. I suspect that it's the 
problem.
Without SyntaxKind it works.
```

Original comment by `angelo.z...@gmail.com` on 13 Nov 2013 at 9:00

**Comment by GoogleCodeExporter** [comment]
```
effectively, without SyntaxKind it's ok.
thanks a lot
Régis
```

Original comment by `rba...@gmail.com` on 14 Nov 2013 at 7:00

**Comment by GoogleCodeExporter** [comment]
```
I close this invalid issue.
```

Original comment by `angelo.z...@gmail.com` on 14 Nov 2013 at 7:56
- Changed state: **Invalid**
