### ISSUE TITLE
Error: fr.opensagres.xdocreport.converter.XDocConverterException: java.lang.NoClassDefFoundError: com/lowagie/text/Element

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dbarra/xdocreport#40]
```
What steps will reproduce the problem?
1. Create Java Project in Eclipse with Class DocxProjectWithVelocity2PDF
2. Adding all jar's corresponding to 
http://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainConverter
3. Saving and run class DocxProjectWithVelocity2PDF will provide the error

What is the expected output? What do you see instead?
PDF File --> DocxProjectWithVelocity_Out.pdf

What version of the product are you using? On what operating system?
- fr.opensagres.xdocreport.samples.docxandvelocity.converters-0.9.1
- plus iText-5.0.6.jar
- I tried with jre 1.5.0, 1.6.0 and 1.6.07 

Please provide any additional information below.
Here is the fully error message from the console

fr.opensagres.xdocreport.converter.XDocConverterException: 
java.lang.NoClassDefFoundError: com/lowagie/text/Element
    at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:570)
    at fr.opensagres.xdocreport.samples.docxandvelocity.DocxProjectWithVelocity2PDF.main(DocxProjectWithVelocity2PDF.java:39)
Caused by: java.lang.NoClassDefFoundError: com/lowagie/text/Element
    at org.apache.poi.xwpf.converter.itext.XWPF2PDFViaITextConverter.doConvert(XWPF2PDFViaITextConverter.java:52)
    at org.apache.poi.xwpf.converter.itext.XWPF2PDFViaITextConverter.doConvert(XWPF2PDFViaITextConverter.java:37)
    at org.apache.poi.xwpf.converter.internal.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:42)
    at fr.opensagres.xdocreport.converter.docx.poi.itext.XWPF2PDFViaITextConverter.convert(XWPF2PDFViaITextConverter.java:61)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:544)
    ... 1 more
Caused by: java.lang.ClassNotFoundException: com.lowagie.text.Element
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 6 more

```

Original issue reported on code.google.com by `omied.am...@gmail.com` on 16 Sep 2011 at 2:48

**Comment by GoogleCodeExporter** [comment]
```
There was an error in the 
http://code.google.com/p/xdocreport/wiki/DocxReportingJavaMainConverter which 
use bad version of iText. The itext version to use is itext-2.1.7.jar.


```

Original comment by `angelo.z...@gmail.com` on 16 Sep 2011 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
Issue 39 has been merged into this issue.
```

Original comment by `pascal.leclercq` on 16 Sep 2011 at 3:53

**Comment by GoogleCodeExporter** [comment]
Original comment by `angelo.z...@gmail.com` on 1 Nov 2011 at 3:52
- Changed state: **Done**

**Comment by GoogleCodeExporter** [comment]
```
cleanup
```

Original comment by `pascal.leclercq` on 10 Oct 2014 at 7:37
