### ISSUE TITLE
Exception with big DOCx file -> PDF 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dbarra/xdocreport#49]
```
What steps will reproduce the problem?
1. Choose DocxBig.docx on 
http://xdocreport.opensagres.cloudbees.net/processReport.jsp
2. Then Choose conversion "To PDF via iText"

What is the expected output? What do you see instead?
The result is a Java Exception

What version of the product are you using? On what operating system?


Please provide any additional information below.


```

Original issue reported on code.google.com by `bernardm...@gmail.com` on 26 Oct 2011 at 1:59
- Merged into: #47

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I don't understand your issue. When I go at 
http://xdocreport.opensagres.cloudbees.net/processReport?dispatch=load&converter
=PDF_ITEXT&reportId=DocxBig.docx to convert DocxBig.docx to PDF, it works?

What is your exception?

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 27 Oct 2011 at 7:00
- Changed title: *_Exception with big DOCx file -> PDF *_
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Ok,

It was a cache problem I think. Now I have the error : 

--------------------------------------------------------------------------------
-
java.lang.NullPointerException
    at fr.opensagres.xdocreport.document.docx.preprocessor.DocxBufferedDocument.onEndEndElement(DocxBufferedDocument.java:229)
    at fr.opensagres.xdocreport.document.preprocessor.sax.BufferedDocumentContentHandler.endElement(BufferedDocumentContentHandler.java:185)
--------------------------------------------------------------------------------
-

It's a bug with Hyperlink TOC the same bug than 
http://code.google.com/p/xdocreport/issues/detail?id=47 that I have fixed and 
commited in the Git repository.

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 27 Oct 2011 at 8:30

**Comment by GoogleCodeExporter** [comment]
Original comment by `angelo.z...@gmail.com` on 1 Nov 2011 at 3:51

**Comment by GoogleCodeExporter** [comment]
Original comment by `angelo.z...@gmail.com` on 1 Nov 2011 at 6:49
- Changed state: **Duplicate**
