### ISSUE TITLE
ClassCastException when rendering a document

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dbarra/xdocreport#67]
```
I am facing the following exception when rendering a document in 0.9.4. It 
works fine on 0.9.2.

fr.opensagres.xdocreport.core.io.MultiWriter cannot be cast to 
fr.opensagres.xdocreport.core.io.StreamCancelable
    at fr.opensagres.xdocreport.document.preprocessor.AbstractXDocPreprocessor.preprocess(AbstractXDocPreprocessor.java:117)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.doPreprocessorIfNeeded(AbstractXDocReport.java:312)
    at fr.opensagres.xdocreport.document.AbstractXDocReport.convert(AbstractXDocReport.java:549)


What version of the product are you using? On what operating system?
0.9.4


```

Original issue reported on code.google.com by `gegasta...@gmail.com` on 15 Jan 2012 at 5:49

**Comment by GoogleCodeExporter** [comment]
```
Hi Georges,

This bug comes from when we have integrated logs in 0.9.3. I have fixed the 
problem with ClassCastException in the Git (XdocReport 0.9.5) by implementing 
StreamCancelable for MultiWriter.

But this case comes from when you have log (ex : log4j, sfl4j ...) activated 
and error done while preprocessing state. So I think you have error with your 
documentation. Please try with 0.9.5 fix and I think you will see your real 
error (hope it's not a new bug).

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 16 Jan 2012 at 12:15
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `angelo.z...@gmail.com` on 19 Jan 2012 at 11:46

**Comment by GoogleCodeExporter** [comment]
```
Hi Georges,

Do you have trouble with 0.9.6 version? I would like fix this bug please.

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 26 Feb 2012 at 10:47

**Comment by GoogleCodeExporter** [comment]
```
No problem at all ! Just checked and this bug is fixed.

Regards,

George
```

Original comment by `gegasta...@gmail.com` on 27 Feb 2012 at 11:19

**Comment by GoogleCodeExporter** [comment]
```
Many thanks George.

I fix the bug.

Regards Angelo
```

Original comment by `angelo.z...@gmail.com` on 28 Feb 2012 at 8:18
- Changed state: **Fixed**
